# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-US"
title: "Lukas Vermeer"
title_separator: "|"
subtitle: "Chief Experimentation Officer"
name: "Lukas Vermeer"
email: lukas@lukasvermeer.nl
description: >- # this means to ignore newlines until "baseurl:"
  I help people run experiments to make better products for customers. I explain
  science using historical narratives and teach statistics through storytelling.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.lukasvermeer.nl" # the base hostname & protocol for your site, e.g. http://example.com
teaser: /assets/images/header-bg.webp
og_image: /assets/images/header-bg.webp
repository: lukasvermeer/lukasvermeer.github.io

twitter:
  username: "lukasvermeer"
github_username:  lukasvermeer

social:
  type: "Person" # Person or Organization (defaults to Person)
  name: "Lukas Vermeer" # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/lukasvermeer"
    - "https://www.linkedin.com/in/lukasvermeer"

analytics:
  provider: "custom"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lukasvermeer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lukasvermeer"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/lukasvermeer"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

atom_feed:
  hide: true

compress_html:
  clippings: all

minimal_mistakes_skin: contrast
breadcrumbs: false
show_date: true

author:
  name     : "Lukas Vermeer"
  avatar   : "/assets/images/bio-photo.webp"
  bio      : "I help people run experiments to make better products for customers."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lukasvermeer"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/lukasvermeer"

defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      author_profile: true
      layout: single
      permalink: /publications/:categories/:year/:month/:day/:title:output_ext
      read_time: true
      share: true
      related: true
  - scope:
      path: ""
      type: "pages"
    values:
      feature_row_questions:
        - image_path: /assets/images/header-questions.webp
          alt: "Lukas sitting in the crows raising his hand high to ask a question at a Booking Data Science Conference in Amsterdam, 2018."
          image_caption: "Booking Data Science Conference, Amsterdam (2018)"
          title: "Asking questions is my superpower"
          excerpt: 'Are you familiar with the Socratic method? If not, perhaps you should Google it. Asking questions is a powerful way to stimulate critical thinking and foster understanding. My strength as a speaker and advisor does not stem from having all the answers, but from relentlessly asking the right questions.'
      feature_row_listening:
        - image_path: /assets/images/header-feedback.webp
          alt: "Lukas on stage with hands behind ears listening to the crowd at Predictive Analytics World in Berlin, 2017."
          image_caption: "Predictive Analytics World, Berlin (2017)"
          title: "Listening is my secret weapon"
          excerpt: 'Being able to speak is not enough. Great presenters pay close attention to their audience and invite authentic interactions with the crowd. Expert advisors will watch and observe before they speak. I understand my role—as a presenter or consultant—is not just to talk, but perhaps more importantly to listen.'
      feature_row_bookme:
        - image_path: /assets/images/header-teaching.webp
          alt: "Lukas on stage explaining p-values to a crowd of Marketing professionals at Digital Growth Unleashed in London, 2017."
          image_caption: "Digital Growth Unleashed, London (2017)"
          title: "Let's talk"
          excerpt: 'Interested? Reach out over [LinkedIn](https://www.linkedin.com/in/lukasvermeer/) or [book some of my time](/booktime/) for a chat or an email.'
          url: "/booktime/"
          btn_label: "Book my time &#8594;"
          btn_class: "btn--primary"

include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
